# Generated by Django 5.0.1 on 2024-01-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_finished_tasks_profile_total_collections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_goals',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
