# Generated by Django 3.2 on 2024-01-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_collections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcollection',
            name='tasks',
        ),
    ]
