# Generated by Django 3.2 on 2024-01-16 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20240116_1344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='id_done',
            new_name='is_done',
        ),
    ]
